#ifndef CONFIG_h
#define CONFIG_h

#define CHUNK_HEIGHT 4
#define CHUNK_WIDTH  4

#define CHUNK_START_X 6
#define CHUNK_START_Y 6

#define FIELD_HEIGHT 24
#define FIELD_WIDTH  16

#define FIELD_HEIGHT_UPPER_INDEX 4
#define FIELD_WIDTH_LEFT_INDEX   3
#define FIELD_WIDTH_RIGHT_INDEX 12

#endif